### ISSUE TITLE
README.m usage imports

### ISSUE THREAD

**Issue by psimk** [fusionjs/fusion-core#259]
### Type of issue

Documentation mistake

### Description

The sentence before 'Table of Contents' states:
`If you're using React, you should use the **fusion-react** package instead of fusion-core.`
However, the usage example uses the **fusion-core** package.

### Steps to reproduce

goto: [README](https://github.com/fusionjs/fusion-core#usage)

### Your environment

* Operating System:

Macos 10.13.6,
Firefox (Developer Edition) 62.0b13 (64-bit)

**Comment by KevinGrandon** [comment]
Thank you for the bug report. While you could certainly use fusion-core as a standalone package, we recommend folks use fusion-react, which is a different package. Fusion-react extends fusion-core and provides react-specific implementations. You can find documentation for that package here: https://github.com/fusionjs/fusion-react#usage

Since the documentation for this package (fusion-core), looks correct, I'm going to close this for now. Please feel free to comment if you think there's been a mistake, or if I could clarify anything further.
