### ISSUE TITLE
Support optional dependencies

### ISSUE THREAD

**Issue by lhorie** [fusionjs/fusion-core#95]
Rationale:

Some plugins consume UniversalEvents but only for emission of things like stats. It would make sense for the dependency to be optional, and this ability used to be supported pre-DI.

Deliverable:

Propose a mechanism that would allow plugins to specify dependencies as optional

**Comment by KevinGrandon** [comment]
What about?
```
optionalDeps: {
   dep: Token
}
```

**Comment by ganemone** [comment]
To summarize the two current options:

### Option 1

```js
// Defining the token
import {createToken} from 'fusion-core';
import type {Token} from 'fusion-core';

type Fetch = (input: string | Request, init?: RequestOptions) => Promise<Response>;
export const FetchToken: Token<Fetch> = createToken('FetchToken');

// Using the token
import {createPlugin} from 'fusion-core';
export default createPlugin({
  deps: {
    fetch: FetchToken, // required token example
    logger: LoggerToken.optional, // optional token example
  },
});
```

### Option 2

```js
// Defining the token
import {createToken} from 'fusion-core';

type Fetch = (input: string | Request, init?: RequestOptions) => Promise<Response>;
export const FetchToken: Fetch = createToken('FetchToken');

// Using the token
import {createPlugin} from 'fusion-core';
export default createPlugin({
  deps: {
    fetch: FetchToken, // required token example
  },
  optionalDeps: {
    logger: LoggerToken, // optional token example
  }
});
```

I much prefer the api of option 1, however it comes with the downside of needing to use the `Token` type helper. However, maybe that isn't much of a problem.

**Comment by ganemone** [comment]
### Incorrect Option

```js
// Defining the token
import {createToken} from 'fusion-core';

type Fetch = (input: string | Request, init?: RequestOptions) => Promise<Response>;
export const FetchToken: Fetch = createToken('FetchToken');

// Using the token
import {createPlugin} from 'fusion-core';
export default createPlugin({
  deps: {
    fetch: FetchToken, // required token example
  },
  optionalDeps: {
    logger: LoggerToken, // optional token example
  }
});
```

**Comment by lhorie** [comment]
I think we should explore the type safety of each option

**Comment by ganemone** [comment]
### Option 3

```js
// Defining the token
import {token} from 'fusion-core';

type Fetch = (input: string | Request, init?: RequestOptions) => Promise<Response>;
export const FetchToken: Fetch = token.create('FetchToken');

// Using the token
import {createPlugin} from 'fusion-core';
export default createPlugin({
  deps: {
    fetch: FetchToken, // required token example
    logger: token.optional(LoggerToken), // optional token example
  }
});
````

**Comment by AlexMSmithCA** [comment]
Are there any concerns with comprehension of tokens with these changes?

Option 1 implies that tokens should be created via _createToken_ to be even minimally supported tokens.  It's more to "understand" what a token is, versus pointing to a string and saying "hey, this is a fully supported token if you want it to be!".  Up side is that it's simple to use.

Option 2 expands our surface area API for _createPlugin_ which I think we should have a lot of friction against if we can help it.  What happens with name collisions between `deps` and `optionalDeps`?  Is a single `deps` object still provided to the `provides` and `middleware` methods?

Option 3 maintains the simplicity of tokens while providing a helper function to expand functionality on _any_ valid token if necessary.  It isn't super clean, however ([decorators](https://en.wikipedia.org/wiki/Decorator_pattern), anybody?).  Up side is that it doesn't deepen the learning curve for Fusion as it's an "advanced helper".

In any case, this adds an additional gating mechanism - and complexity - where now both token authors _and_ consumers via plugins will have the ability to effectively turn the tokens on or off.  So we should also think about renaming `createOptionalToken` since it doesn't really do that anyway.

**Comment by AlexMSmithCA** [comment]
### Option 3

Disallow optional constructor-injected parameters.  Instead allow the user to inject `null`.

```js
// Defining the token
import {token} from 'fusion-core';

type Fetch = (input: string | Request, init?: RequestOptions) => Promise<Response>;
export const FetchToken: Fetch = token.create('FetchToken');

// Using the token
import {createPlugin} from 'fusion-core';
export default createPlugin({
  deps: {
    fetch: FetchToken, // required token example
    logger: ?LoggerToken, // null-able token example
  }
});

// main.js
const app = new App(...);
app.register(FetchToken, /*someFetch*/);
app.register(LoggerToken, null);
````

**Comment by AlexMSmithCA** [comment]
### Option 5

Disallow optional constructor-injected parameters (a.k.a. what we have today)

Pros:
* No additional complexity
* No additional work

Cons:
* All constructor-injected parameters must be supplied.

In the canonical emitter case, the plugins would assume that something that matches the expected API is provided and it would be up to us (as token authors) to provide a no-op as the default value if the token is not registered.

**Comment by rtsao** [comment]
Are there more concrete use cases for optional dependencies? As @AlexMSmithCA mentions, some noop value can always be registered.

**Comment by lhorie** [comment]
@rtsao the main use case is in the OP (optional UniversalEvents for stat emission). Another use case is configuration, which is currently handled via createOptionalToken, but I think optionality should be handled by the same concept for both plugins and config values rather than having different ad-hoc mechanisms for each. A related use case is that some Uber-specific plugins optionally depend on various clients (e.g. to add transports)

The downside of registering a noop is that you then increase barrier to entry by requiring that someone register things manually that don't necessarily need to be. I expect that the typical OSS argument will be: "why use this over-engineering thing that needs scaffolding if Next.js/Electrode/Sapper don't have all that needless boilerplate"
